services:
  # baseline:
  #   build:
  #     dockerfile: Dockerfile.baseline
  #   container_name: baseline
  #   volumes:
  #     - .:/app 
  #   command: python /app/src/main_baseline.py
  
  ray:
    build:
      dockerfile: Dockerfile.ray
    container_name: ray
    shm_size: '4gb'
    volumes:
      - .:/app
    command: python /app/src/main_ray.py
  
  # spark:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: spark
  #   volumes:
  #     - .:/app 
  #   command: python /app/src/spark_main.py

  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: celery
  #   depends_on:
  #     - redis-celery
  #   volumes:
  #     - .:/app 
  #   command: celery -A tasks worker --loglevel=INFO --concurrency=2
  
  # redis-celery:
  #   image: redis
  #   container_name: redis_celery
  #   port: 
  #     - 6379:6379